services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - items-db:/var/lib/postgresql/data

  project_purple_cow:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  items-db:
